### PR TITLE
fix: revamp bundler to use optimization mode

### PR DESCRIPTION
**Pull request by vcnc-hex**
Image optimization should be able to convert modern format like `webp` if client be supported by adding the mime type to Accepts header. But, It doesn't be compressed to `webp` format, and the resizing and rotation functions do not work either. Internally, Next.js uses `squoosh` lib, but `@vercel/nft` couldn't include that files.
So, I just add `squoosh` files in the `node_modules` to solve the problem.

### CODE REVIEW

**Comment by ofhouse** [comment]
Oh nice catch, wondered why several formats could not be converted to webp before but never realized that most of the squoosh library was not added to the bundle.

Seems like the e2e tests must also be adjusted to reflect this change.
Are you able to run the tests locally or should I take a look?

**Comment by vcnc-hex** [comment]
@ofhouse Sure, I can do myself to fix the snapshots applied this change for e2e tests.

**Review by ofhouse — APPROVED** [review]
LGTM, thanks for the contribution!
Will release this together with the upcoming Next.js version (that should be released after the Next.js Conf later today)

**Comment by ofhouse** [comment]
This has now be published in the [v11.0.0 ](https://github.com/dealmore/terraform-aws-next-js-image-optimization/releases/tag/v11.0.0) release. 🚀

**Pull request merged**
